### ISSUE TITLE
Add a label to node

### ISSUE THREAD

**Issue by gangadhars** [kelproject/pykube#106]
How to add a label to node?

I'm not sure how to do it from pykube. Here is what I have tried:
```python
import operator
import pykube

obj =  {
 "op": "add", "path": "/metadata/labels/disk", "value": "ssd"
 }

api = pykube.HTTPClient(pykube.KubeConfig.from_file("/home/user/.kube/config"))
pykube.Node(api, obj).update().filter(name="172.16.2.152")
```
And getting below error:
```bash
Traceback (most recent call last):
  File "node_update_label.py", line 9, in <module>
    pykube.Node(api, obj).update().filter(name="172.16.2.152")
  File "/usr/local/lib/python2.7/dist-packages/pykube/objects.py", line 106, in update
    data=json.dumps(self.obj),
  File "/usr/local/lib/python2.7/dist-packages/pykube/objects.py", line 71, in api_kwargs
    kw["url"] = op.normpath(op.join(self.endpoint, self.name, operation))
  File "/usr/local/lib/python2.7/dist-packages/pykube/objects.py", line 49, in name
    return self.obj["metadata"]["name"]
KeyError: 'metadata'
```
Thank you

**Comment by gangadhars** [comment]
I understand how to add a label to node..

```python
import operator
import pykube

obj = {
    "apiVersion": "v1",
    "kind": "Node",
    "metadata": {
        "name": "172.16.2.152",
        "labels": {
            "disk": "ssd"
        }
    }
}

api = pykube.HTTPClient(pykube.KubeConfig.from_file("/home/user/.kube/config"))
pykube.Node(api, obj).update()
```
Thanks
