### ISSUE TITLE
ssl.SSLError when connecting to 1.3 GKE cluster

### ISSUE THREAD

**Issue by paultiplady** [kelproject/pykube#58]
I've just upgraded my GKE cluster to version 1.3, and I'm now getting an SSL error when trying to connect using pykube:

```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): <snip>
Traceback (most recent call last):
  File "/Users/paul/.virtualenvs/deploy/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/Users/paul/.virtualenvs/deploy/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 351, in _make_request
    self._validate_conn(conn)
  File "/Users/paul/.virtualenvs/deploy/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 814, in _validate_conn
    conn.connect()
  File "/Users/paul/.virtualenvs/deploy/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "/Users/paul/.virtualenvs/deploy/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ssl.py", line 583, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/paul/.virtualenvs/deploy/lib/python3.4/site-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/Users/paul/.virtualenvs/deploy/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 604, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "deploy.py", line 97, in <module>
    main()
  File "deploy.py", line 90, in main
    deploy.create_namespace()
  File "deploy.py", line 29, in create_namespace
    pykube.Namespace(self.api, {'metadata': {'name': self.namespace}}).create()
  File "/Users/paul/.virtualenvs/deploy/lib/python3.4/site-packages/pykube/objects.py", line 62, in create
    r = self.api.post(**self.api_kwargs(data=json.dumps(self.obj), collection=True))
  File "/Users/paul/.virtualenvs/deploy/lib/python3.4/site-packages/pykube/http.py", line 153, in post
    return self.session.post(*args, **self.get_kwargs(**kwargs))
  File "/Users/paul/.virtualenvs/deploy/lib/python3.4/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/paul/.virtualenvs/deploy/lib/python3.4/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/paul/.virtualenvs/deploy/lib/python3.4/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/Users/paul/.virtualenvs/deploy/lib/python3.4/site-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:600)
```

I can interact with the system using `kubectl`, so doesn't look like a cluster problem at first pass.

Have you tested pykube with 1.3 yet? Is there known to be work required to support the new version?

**Comment by paultiplady** [comment]
Ok, I've figured this out.

Digging into the error a bit more, the server is rejecting the TLS Client Hello, because TLS v1.0 is unsupported on GKE 1.3.

How do we select the TLS version? In general this can be easily overridden in Requests (see [this guide](https://lukasa.co.uk/2013/01/Choosing_SSL_Version_In_Requests/). But Requests lets urllib3 choose the default TLS version, which is usually the best available; that in turn depends on the installed version of OpenSSL:

```
>>> import ssl
>>> ssl.PROTOCOL_TLSv1_2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'PROTOCOL_TLSv1_2'
>>> ssl.OPENSSL_VERSION
'OpenSSL 0.9.8zh 14 Jan 2016'
```

Turns out on MacOS, the bundled OpenSSL version is antiquated. This also turns out to be much more of a pain to fix than expected; I'm using Python3.4, and Homebrew doesn't maintain pre-3.5 versions of Python3, so the following fix turned out to be the best for me: 

http://stackoverflow.com/a/37757206/37481

For posterity, reproduced here, assuming a fully-configured pyenv install:

```
brew update
brew install openssl
brew link --force openssl

CFLAGS="-I$(brew --prefix openssl)/include" \
LDFLAGS="-L$(brew --prefix openssl)/lib" \
pyenv install -v 3.4.4
```

Sadly it doesn't appear to be sufficient to install a new openssl; a new Python must be installed and linked against the new OpenSSL.
